### ISSUE TITLE
Do you have a working client?

### ISSUE THREAD

**Issue by ignis-sec** [Hydroque/BOUT-BOTs-Server#1]
Hello, do you have a working client for this?

**Comment by ignis-sec** [comment]
I know im probably a few years late, but i hate old online games dying, so i recreate them for preservation.

I want to recreate bots, however, old clients source codes are long gone from the internet. Closest suitable candidate i have is the bots original client (which somehow survived) but i hate working on binary reverse engineering, and cant bypass the nGameGuard subroutine that stops the game after a minute. I have seen you made a lot of effort on the serverside back in the time, so i figured maybe you had a bypassed client.

I would appreciate any help you could provide.

**Comment by tilkinsc** [comment]
Good question. Email me.

**Comment by tilkinsc** [comment]
@FlameOfIgnis I am working on this project again. I sent you a discord friend request.

**Comment by tilkinsc** [comment]
@ignis-sec do you have the database files for #2
